from rank_bm25 import BM25Okapi
import numpy as np
from sentence_transformers import CrossEncoder

class HybridSearchRRF:
    def __init__(self, vector_store, bm25_corpus, cross_encoder_model="BAAI/bge-reranker-v2-m3"):
        self.vector_store = vector_store
        
        # Initialize BM25 search
        tokenized_corpus = [doc.split(" ") for doc in bm25_corpus]
        self.bm25 = BM25Okapi(tokenized_corpus)
        self.bm25_corpus = bm25_corpus
        
        # Initialize Cross-Encoder for reranking
        self.cross_encoder = CrossEncoder(cross_encoder_model)
        
    def vector_search(self, query, top_k=50, filter_params=None):
        """
        Vector search with explicit RBAC pre-filtering via Qdrant.
        filter_params should be a qdrant_client.http.models.Filter object
        (e.g., generated by security.get_rbac_filter()).
        """
        from qdrant_client.http import models

        # Build the Qdrant search request with RBAC filter enforcement
        search_result = self.vector_store.query(
            query_text=query,
            limit=top_k,
            # RBAC: Pre-filter unauthorized documents (e.g., FIOD) at the DB level
            # before they ever reach the application layer.
            query_filter=filter_params  # models.Filter from security.get_rbac_filter()
        )

        # Normalize results to (document_id, score) tuples
        return [(hit.id, hit.score) for hit in search_result]

    def bm25_search(self, query, top_k=10):
        """BM25 keyword search."""
        tokenized_query = query.split(" ")
        scores = self.bm25.get_scores(tokenized_query)
        top_n = np.argsort(scores)[::-1][:top_k]
        return [(self.bm25_corpus[i], scores[i]) for i in top_n]

    def rrf(self, vector_results, bm25_results, k=60):
        """Reciprocal Rank Fusion (RRF)."""
        rrf_scores = {}
        
        for rank, (doc_id, score) in enumerate(vector_results):
            if doc_id not in rrf_scores:
                rrf_scores[doc_id] = 0
            rrf_scores[doc_id] += 1 / (k + rank + 1)
            
        for rank, (doc_id, score) in enumerate(bm25_results):
            if doc_id not in rrf_scores:
                rrf_scores[doc_id] = 0
            rrf_scores[doc_id] += 1 / (k + rank + 1)
            
        sorted_rrf = sorted(rrf_scores.items(), key=lambda x: x[1], reverse=True)
        return sorted_rrf

    def rerank(self, query, documents, top_k=5):
        """Cross-encoder reranking."""
        pairs = [[query, doc[0]] for doc in documents]
        scores = self.cross_encoder.predict(pairs)
        
        reranked = [(documents[i][0], scores[i]) for i in range(len(scores))]
        reranked.sort(key=lambda x: x[1], reverse=True)
        
        return reranked[:top_k]

    def search(self, query, initial_top_k=50, final_top_k=5, filter_params=None):
        # 1. Hybrid Search: Wide net retrieval (Vector + BM25) with RBAC enforcement
        vector_res = self.vector_search(query, top_k=initial_top_k, filter_params=filter_params)
        bm25_res = self.bm25_search(query, top_k=initial_top_k)
        
        # 2. Reciprocal Rank Fusion to merge both result sets
        rrf_res = self.rrf(vector_res, bm25_res)
        
        # 3. Cross-encoder reranking: Narrow funnel to final_top_k precision results
        final_results = self.rerank(query, rrf_res, top_k=final_top_k)
        
        return final_results
